### ISSUE TITLE
Phrasing

### ISSUE THREAD

**Issue by WritingPanda** [sharifhkhan/jsdevenv#1]
> Use localtunnel to expose yourself

I know what you meant, but there has to be a better way of saying that.

**Comment by sharifhkhan** [comment]
[_Expose yourself to the world_](https://localtunnel.github.io/www/) 
It is literally the tagline. 

[![](https://img.youtube.com/vi/ZXsQAXx_ao0/0.jpg)](https://www.youtube.com/watch?v=ZXsQAXx_ao0)
